.\" Manpage for vsh.
.\" Contact antoine.prudhomme@utt.fr or mathilde.sandor@utt.fr to correct errors or typos.
.TH man 1 "14 June 2018" "1.0" "vsh man page"

.SH NAME
vsh \- the vsh client tool 

.SH SYNOPSIS
\fBvsh\fR --help
.br
\fBvsh\fR \fICOMMAND\fR \fIHOST\fR \fIPORT\fR [\fIARCHIVE_NAME\fR]

.SH DESCRIPTION
\fBvsh\fR allows you to interact with an archive server that supports \fBvsh\fR. It handle the basics operations, like listing the archives stored on a server, extract an archive on your machine, and even executing classical Linux commands while browsing an archive stored on the server.

.SH COMMANDS
\fBvsh\fR supports the following commands. For each one, the \fBhost\fR and host's \fBport\fR are required. 
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-help\fR
.sp
Display a help message on the standard output and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-list\fR \fIHOST\fR \fIPORT\fR
.sp
List all the archives saved on the given server on the standard output\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-extract\fR \fIHOST\fR \fIPORT\fR \fIARCHIVE_NAME\fR
.sp
Extracts the given archive from the given server at the location where the client runs the command. It will create all the directories and files, with their contents\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-browse\fR \fIHOST\fR \fIPORT\fR \fIARCHIVE_NAME\fR
.sp
Open a \fBvsh shell\fR in the given archive from the given server. This shell allows you to run some classical Linux commands, as if you where in the extracted archive for real. All the commands you run update the original archive on the server. These commands are detailed in the next section\&.
.sp
You know you are in a \fBvsh shell\fR because your prompt will change to something like this: 
.br
\fBvsh@host:port {archive_name} path :>\fR
.RE

.SH VSH SHELL COMMANDS
These commands can be run when you are in a \fBvsh shell\fR, and will update the archive you are browsing.
All paths can be both absolute to the archive's root, or relative to the working directory.

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBpwd\fR
.sp
Print the name of the working directory\&.
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBls\fR [\fIDIRECTORY\fR]
.sp
List the content of DIRECTORY (the working directory by default). Directories are followed by \fB/\fR and executable files by \fB*\fR\&.
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBcd\fR \fIDIRECTORY\fR
.sp
Change the working directory to DIRECTORY\&.
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBcat\fR \fIFILE\fR
.sp
Print the content of FILE on the standard output\&.
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBrm\fR \fIFILE\fR
.sp
Remove FILE\&.
.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBrmdir\fR \fIDIRECTORY\fR
.sp
Remove DIRECTORY\&.
.RE

.SH BUGS
No known bugs.

.SH AUTHORS
Antoine PRUDHOMME (antoine.prudhomme@utt.fr)
.br
Mathilde SANDOR (mathilde.sandor@utt.fr)